services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrong!Pass123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - booxer_net

  backend:
    build:
      context: .
      dockerfile: Booxer.Web/API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - DATABASE_URL=Server=db;Database=BooxerDb;User Id=sa;Password=YourStrong!Pass123;TrustServerCertificate=true;Encrypt=true;
      - JWT_SECRET_KEY=demosecretkey204398572304958723409857230948572309485723094857234
      - CORS_ORIGINS=http://localhost:4200
    depends_on:
      - db
    networks:
      - booxer_net

  frontend:
    build:
      context: .
      dockerfile: Booxer.Web/UI/Dockerfile
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./Booxer.Web/UI:/app
      - /app/node_modules


networks:
  booxer_net:
    driver: bridge

volumes:
  sql_data: